export { default as ProjectAnalysis } from './ProjectAnalysis'
export { default as ProjectDetails } from './ProjectDetails'
export { default as MachineAnalysis } from './MachineAnalysis'
export { default as CustomerStatistics } from './CustomerStatistics'
export { default as OEE } from './OEE'
export { default as OEERedesign } from './OEE'
export { default as EmployeesDesignations } from './EmployeesDesignations'
export { default as AdminPanel } from './AdminPanel'
